### ISSUE TITLE
Include source IP Address in all JSON entries

### ISSUE THREAD

**Issue by brianwarehime** [micheloosterhof/kippo#16]
Michel,

I was wondering if you considered including the source IP address in every event in the JSON format. It has the session ID in there, which is great, but, it would help me out a lot if it included the source IP as well. I aggregate my logs using Splunk, and it makes the searches a bit more costly to run because it needs to search through the whole session to grab the source IP. 

I'm not sure what your thoughts are on that matter, but it would definitely help me out.

Thanks!

Brian

**Comment by micheloosterhof** [comment]
Hi,

I welcome the suggestion. I initially used the design from the dblog module, which works with sessionid to distinguish the different log entries. The sessionid's are useful become sometimes I see multiple simultaneous connections from a single source IP, and the source IP by itself is not a unique identifier anymore. Which is why I'd hesitate a little to add it back.

I assume you want to Src IP in every field because you want to do some processing of the data. Could you give me an idea of what exactly you want to do? Maybe there's another way around it, or maybe that'll tell us there's no other way than add the IP into every entry.

Michel.

**Comment by brianwarehime** [comment]
Michel,

So, I definitely understand why the session ID is important, and I’m glad it’s there. I just wanted to add the src_ip to each event, since when I try to run the searches in Splunk, it takes a while to grab the source IP.

For example, when I try to grab the source IP address of the attacker in each session, I need to run a ‘transaction’ command, which groups like events together based on their session ID. This is pretty expensive and takes a while to run, whereas if the src_ip was included in each event, it would be easy and quicker to run searches.

It’s definitely possible to get the information I need, but, again, it just makes Splunk run a little harder and take longer to produce results without the source IP in every event. Is there any big reason why we shouldn’t add that in? 

Again, this is only for a small use-case, so, I don’t think you should add it to just help me out. But, if others could benefit from it, then maybe it would be good to add?

Just my two cents. Thanks for the response!

Brian




On February 25, 2015 at 12:31:19 AM, Michel Oosterhof (notifications@github.com) wrote:

Hi,

I welcome the suggestion. I initially used the design from the dblog module, which works with sessionid to distinguish the different log entries. The sessionid's are useful become sometimes I see multiple simultaneous connections from a single source IP, and the source IP by itself is not a unique identifier anymore. Which is why I'd hesitate a little to add it back.

I assume you want to Src IP in every field because you want to do some processing of the data. Could you give me an idea of what exactly you want to do? Maybe there's another way around it, or maybe that'll tell us there's no other way than add the IP into every entry.

Michel.

**Comment by micheloosterhof** [comment]
Brian,
Thanks. I still have more questions though  :)

If you want to make output based on attacker IP address, I imagine the only thing you'd need to look at is the connection requests, and those already include the IP address. There is no need (I imagine) to look at the other log entries (such as command found/not found, etc)

Unless you want to see (for example) which command was executed from each IP address, wouldn't it be better to do a select (or whatever appropriate name it has in Splunk) to see only connection requests?

The only use case I could imagine was to distinguish between scanning only machines (which do SSH request), password guessers (which do login success/failure) and remote control machines (which actually run commands)

regards,

Michel.

**Comment by brianwarehime** [comment]
Michel,

I think the best way to illustrate what I’m talking about is to show you what I’m working on. Could you shoot me an email at brianwarehime@gmail.com whenever you’re free and we can do a quick webex using Google Hangouts or whatever works best for you. I think this would help show why I could benefit from the IP.

Thanks!

Brian




On February 25, 2015 at 11:42:59 AM, Michel Oosterhof (notifications@github.com) wrote:

Brian,
Thanks. I still have more questions though :)

If you want to make output based on attacker IP address, I imagine the only thing you'd need to look at is the connection requests, and those already include the IP address. There is no need (I imagine) to look at the other log entries (such as command found/not found, etc)

Unless you want to see (for example) which command was executed from each IP address, wouldn't it be better to do a select (or whatever appropriate name it has in Splunk) to see only connection requests?

The only use case I could imagine was to distinguish between scanning only machines (which do SSH request), password guessers (which do login success/failure) and remote control machines (which actually run commands)

regards,

Michel.

**Comment by micheloosterhof** [comment]
This has been added the the output plugin system. Currently works with JSON plugin only.
