### ISSUE TITLE
Add IP source address to log entries

### ISSUE THREAD

**Issue by micheloosterhof** [micheloosterhof/kippo#18]
For easy graphs on key-exchange / login / commands per IP address

**Comment by katkad** [comment]
it will be something like self.honeypot.realClientIP
like here https://github.com/csirt-cz/kippo/commit/35eda6b631a0ff711bc716e35448a4aed8594e39

**Comment by micheloosterhof** [comment]
Yeah, two ways of doing it, either add explicitly to a few log messages where it's important.
Or extend dblog to put it in every log message.

**Comment by micheloosterhof** [comment]
Added to output plugin mechanism.
