### ISSUE TITLE
motd returned on ssh_exec

### ISSUE THREAD

**Issue by thinksilicon** [micheloosterhof/kippo#19]
When running ssh with remote command execution (ssh root@host "id") the motd is returned before the command. The expected behaviour is just returning the output of the command.

### Honeypot behaviour
    me@home:~> ssh root@host "id"
    Password:
    
    The programs included with the Debian GNU/Linux system are free software;
    the exact distribution terms for each program are described in the
    individual files in /usr/share/doc/*/copyright.
    
    Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
    permitted by applicable law.
    
    uid=0(root) gid=0(root) groups=0(root)
    me@home:~>

### Expected behaviour
On a real host this should look like:

    me@home:~> ssh user@realhost "id"
    user@realhost's password: 
    uid=1000(user) gid=100(users) groups=100(users)
    me@home:~>

**Comment by micheloosterhof** [comment]
Hi! Confirmed it's the wrong behavior. I'll look into how much effort it is to fix.

**Comment by micheloosterhof** [comment]
Fixed! Thanks for the report.

**Comment by thinksilicon** [comment]
Wow, that was a quick fix. Thank you very much!
