### ISSUE TITLE
Use client IP address in auth.py?

### ISSUE THREAD

**Issue by honigbij** [micheloosterhof/kippo#20]
I want to use the client IP address in the username/password checking code in auth.py, however I cannot find a way to access the (twisted conch ssh) getpeer() method from auth.py. Is it somehow possible to make the client IP address available in the auth.py classes?

**Comment by micheloosterhof** [comment]
Hi!
In the standard Twisted implementation, the IP address is not directly available as far as I can see. I did found this though, which may help you along:

http://stackoverflow.com/questions/9963569/track-ip-of-ssh-login-attempts-with-twisted-conch

**Comment by micheloosterhof** [comment]
This is also related to issue #14

**Comment by honigbij** [comment]
Ok, I finally managed to get this right. In auth.py I added 2 implementation classes for 2 new credentialInterfaces: UsernamePasswordIP and PluggableAuthenticationModulesIP.
Then in the HoneyPotSSHUserAuthServer(userauth.SSHUserAuthServer) class in ssh.py I added (and overrode) the 2 methods: def auth_password(self, packet) and def auth_keyboard_interactive(self, packet).

In the overridden methods I pass the client src IP address to the 2 new credentialInterfaces.
By doing so we have the src IP address available in the requestAvatarId method in HoneypotPasswordchecker and this can be passed to other methods like checkUserPassword.

When I have cleaned up the code I will put it in my fork.

**Comment by micheloosterhof** [comment]
Great! I'll be waiting for your pull request.

**Comment by honigbij** [comment]
Ok, I have submitted the pull request. Apart from updates in ssh.py and auth.py it also includes an example auth.ip-example.py which can be used as an alternative for auth.py and includes a checklogin method that allows clients to login after a random number of times. I was not sure where to put this example, so I leave it to you what to do with it.

**Comment by micheloosterhof** [comment]
Hi! I saw you closed the pull request, but I haven't integrated the changes yet.
If you'd still like them merged, please reopen.
(I haven't had much time to go through your patches, and I wanted to take a closer look since there were quite a few changes)

Michel.

**Comment by honigbij** [comment]
I am new to github and made my changes in the local master instead of a branch. Now I managed to get a clean master again and I will reissue the pull request for the ip address inclusion (from a branch :-D)

**Comment by micheloosterhof** [comment]
Okay! I also saw you converted some comments in the original ip authentication patch from ''' (triple quote) to # (hash).
They are actually not entirely the same, the ''' are docstrings, so could you leave those in place please?

**Comment by honigbij** [comment]
I created a new pull request #30. An alternative authorization class (instead of UserDB) can now be configured in kippo.cfg. I also added such a class: 'AuthRandom' in auth.py.
Also the IP address is now directly retrieved from the transport class and then passed to the credential interface.

**Comment by honigbij** [comment]
#30 is merged, thanks!
