### ISSUE TITLE
No an Issue, just info needed

### ISSUE THREAD

**Issue by dirtdiver512** [micheloosterhof/kippo#34]
How do you acutally install this?  Iam new to kippo, but do have another version working.  Would like to add the json supprt for ELK integration.

thanks
DD

**Comment by micheloosterhof** [comment]
You don't install this on top of your existing kippo installation, it's a complete replacement. So disable your old version and run this one instead. Check your kippo.cfg for appropriate items and then run ./start.sh. the JSON logging should be enable by default.
