### ISSUE TITLE
not an issue, just a question

### ISSUE THREAD

**Issue by dummys** [micheloosterhof/kippo#5]
Hello,

If I have already a kippo running on my server, what I need to change to run your version ? Can I keep my honeyfs and so on ? Or do I need to reconfigure the whole stuff ?

**Comment by micheloosterhof** [comment]
You should be able to do a drop in replacement. The config file has some
extra directives (sftp, JSON logging) so check those. File system is the
same. (And it's always good practice to make backups)

**Comment by dummys** [comment]
ok thank you

**Comment by micheloosterhof** [comment]
No problem! Let me know how it works out.

**Comment by dummys** [comment]
hmm it's normal that I didn't see the sftp connection on the kippo.log ?

**Comment by micheloosterhof** [comment]
Please provide more detail. If you connect to the honeypot with sftp, you should see that in the logs.

**Comment by dummys** [comment]
I didnt see it in the kippo.log

**Comment by micheloosterhof** [comment]
Were you able to successfully connect? Could you list directories, transfer files?

**Comment by dummys** [comment]
yes Ive send a file and see it in dl directory

**Comment by micheloosterhof** [comment]
That's good. It's very odd that it doesn't show in the logs. Is your logging working correctly otherwise?

**Comment by dummys** [comment]
Yees the last log is updating every time and for the other logs ite in
mysql.

**Comment by micheloosterhof** [comment]
Ah! So you're saying the SFTP logs don't show up in MySQL? That is correct.
I never implemented that.

**Comment by dummys** [comment]
yes but in json ?

**Comment by micheloosterhof** [comment]
Not in JSON either. The JSON logging logs exactly the same as MySQL.
I plan to redo the logging, I think the current approach is cumbersome
where the database logging does regex parsing of the data.
