### ISSUE TITLE
SHA File Hash of Files Downloaded - JSON Format

### ISSUE THREAD

**Issue by brianwarehime** [micheloosterhof/kippo#8]
Is there anyway to include the SHA file hash in the JSON logs when someone downloads a file, like in the standard Kippo logging format? That would be super helpful to me, and so I wouldn't have to manually get it myself. Thanks!

**Comment by micheloosterhof** [comment]
I'm doing a rewrite of the logging infrastructure right now, to make it easier to extend. The current dblog framework is not very extensible. Once that's done, it should be easy to add...

**Comment by micheloosterhof** [comment]
So I've ported @katkad 's shasum patches, and it now stores shasum for wget downloads (not for sftp uploads yet). The shasum also is available as a field in the JSON output. 

I made one small change, the filename of the download is now the shasum, and a symbolic link is created to the old file name convention (date/time/safeurl). Please test if you have the opportunity.

**Comment by brianwarehime** [comment]
Awesome, thanks so much! Will test soon. Quick question, do you have any idea on how to change the timestamp that gets written to kippo.log? I'm trying to add milliseconds (%f) to it, but, unsure of where I need to change the strftime.

**Comment by micheloosterhof** [comment]
The logging is complicated. It's run through Twisted logging framework and
I don't know how to easily modify it. You'd have to investigate the twisted
logging.
See here:
http://stackoverflow.com/questions/17071029/changing-time-format-inside-twisted-matrix-log
The top answer is insightful.

On the other hand, I have added milliseconds to the JSON logging, and you
can use that.

M.

**Comment by micheloosterhof** [comment]
Also, heads up, I will change the logging of the SHA-256 again. Right now it's just too complicated with many log messages for the move of the file. I'll consolidate it to one message with URL, SHA-256 and filesystem location.

Also, if you have more questions, please open different issues. let's keep this one for the shasum logging.
